version: "3.7"

services:
  productsapi:
    build:
      context: ./src/ContosoCrafts.ProductsApi
      dockerfile: Dockerfile
    volumes:
      - ~/.aspnet/https:/https:ro
      - ~/.vsdbg:/remote_debugger:rw
    ports:
      - "80:80"
    depends_on:
      - mongodb

  mongodb:
    container_name: mongo_service
    image: mongo:4.2.8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=contosocrafts
    volumes:
      - ./productdata/products.json:/data/products.json
      - ./productdata/populate.sh:/docker-entrypoint-initdb.d/populate.sh
    ports:
      - "27017:27017"

networks:
  default:
    name: standard_network
    driver: bridge
