version: "3.7"

##### Common logging configuration #####
x-logging: &default-logging
  driver: "fluentd"
  options:
    fluentd-address: "localhost:24224"
    fluentd-async-connect: "true"
    tag: "{{.Name}}-{{.ID}}"

services:
  ##### Website  #####
  website:
    build:
      context: ./src/ContosoCrafts.WebSite
      dockerfile: Dockerfile
    container_name: contoso_website
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    logging: *default-logging

  ##### API #####
  productsapi:
    build:
      context: ./src/ContosoCrafts.ProductsApi
      dockerfile: Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    env_file:
      - .env
    logging: *default-logging

  ##### Checkout Processor #####
  checkoutprocessor:
    build:
      context: ./src/ContosoCrafts.CheckoutProcessor
      dockerfile: Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    env_file:
      - .env
    logging: *default-logging

networks:
  default:
    external:
      name: contoso_steeltoe_network
