version: "3.7"

x-logging: &default-logging
  driver: "fluentd"
  options:
    fluentd-address: "localhost:24224"
    fluentd-async-connect: "true"
    tag: "{{.Name}}-{{.ID}}"
    labels: data, infra

services:
  ##### Website & DAPR Sidecar #####
  website:
    build:
      context: ./src/ContosoCrafts.WebSite
      dockerfile: Dockerfile
    container_name: contoso_website
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    logging: *default-logging

  website_dapr:
    image: "daprio/daprd:0.9.0"
    command:
      [
        "./daprd",
        "-app-id",
        "website",
        "-app-port",
        "80",
        "-placement-address",
        "placement:6000",
        "-config",
        "/dapr/config.yaml",
        "-components-path",
        "/dapr/components",
      ]
    volumes:
      - "./components/local:/dapr/components"
      - "./components/config.yaml:/dapr/config.yaml"
      - ./vault_dev_token:/vault/token
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - website
      - placement
    network_mode: "service:website"
    env_file:
      - .env
    logging: *default-logging

  ##### API & DAPR Sidecar #####
  productsapi:
    build:
      context: ./src/ContosoCrafts.ProductsApi
      dockerfile: Dockerfile
    volumes:
      - ~/.aspnet/https:/https:ro
    env_file:
      - .env
    logging: *default-logging

  productsapi_dapr:
    image: "daprio/daprd:0.9.0"
    command:
      [
        "./daprd",
        "-app-id",
        "productsapi",
        "-app-port",
        "80",
        "-placement-address",
        "placement:6000",
        "-config",
        "/dapr/config.yaml",
        "-components-path",
        "/dapr/components",
      ]
    volumes:
      - "./components/local:/dapr/components"
      - "./components/config.yaml:/dapr/config.yaml"
      - ./vault_dev_token:/vault/token
    depends_on:
      - productsapi
      - placement
    network_mode: "service:productsapi"
    env_file:
      - .env
    logging: *default-logging

  ##### Checkout Processor & DAPR Sidecar #####
  checkoutprocessor:
    build:
      context: ./src/ContosoCrafts.CheckoutProcessor
      dockerfile: Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ~/.aspnet/https:/https:ro
    env_file:
      - .env
    logging: *default-logging

  checkoutprocessor_dapr:
    image: "daprio/daprd:0.9.0"
    command:
      [
        "./daprd",
        "-app-id",
        "checkoutprocessor",
        "-app-port",
        "80",
        "-placement-address",
        "placement:6000",
        "-config",
        "/dapr/config.yaml",
        "-components-path",
        "/dapr/components",
      ]
    volumes:
      - "./components/local:/dapr/components"
      - "./components/config.yaml:/dapr/config.yaml"
      - ./vault_dev_token:/vault/token
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - placement
      - checkoutprocessor
    env_file:
      - .env
    network_mode: "service:checkoutprocessor"
    logging: *default-logging

  ##### Dapr Placement #####
  placement:
    image: "daprio/placement:0.9.0"
    container_name: "placement"
    command: ["./placement", "-port", "6000"]
    ports:
      - "6000:6000"
    env_file:
      - .env
    logging: *default-logging

networks:
  default:
    name: dapr_network
    driver: bridge
