apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: jaeger
  namespace: default
spec:
  type: exporters.zipkin
  metadata:
    - name: enabled
      value: "true"
    - name: exporterAddress
      value: "http://jaeger_server:9411/api/v2/spans"
